import { buildHook } from "@/lib/domain/hook-engine";
import type { Hook } from "@/lib/domain/types";

/**
 * Biblioteca semilla de hooks.
 *
 * Estos hooks son el material de arranque de la demo: representan capturas
 * reales de Reels (transcripción + texto en pantalla) que el creador guardó y
 * que el motor de hooks convirtió en plantilla. En producción esta colección se
 * rellena desde `/api/hooks` (entrada manual, webhook de Zernio o el botón
 * "guardar en el Banco de Hooks" del seguimiento de competidores).
 */

const DAY = 86_400_000;
const NOW = Date.now();
const daysAgo = (days: number) => new Date(NOW - days * DAY).toISOString();

interface HookSeed {
  rawText: string;
  onScreenText: string;
  views: number;
  likes: number;
  saves: number;
  creatorHandle: string;
  creatorPlatform: string;
  sourceUrl: string;
  daysAgo: number;
  tags: string[];
  isFavorite?: boolean;
}

const SEEDS: HookSeed[] = [
  {
    rawText: "Este prompt acaba de destruir 3 horas de edición manual",
    onScreenText: "EL PROMPT QUE ELIMINA 3 HORAS DE EDICIÓN",
    views: 1_284_000,
    likes: 96_400,
    saves: 41_200,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/Cx1aB2cD3eF",
    daysAgo: 3,
    tags: ["edición", "prompt", "ia", "productividad"],
    isFavorite: true,
  },
  {
    rawText: "Deja de publicar todos los días en Instagram",
    onScreenText: "DEJA DE PUBLICAR A DIARIO",
    views: 742_000,
    likes: 58_900,
    saves: 33_100,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/Cx2bC3dE4fG",
    daysAgo: 6,
    tags: ["estrategia", "instagram", "frecuencia"],
    isFavorite: true,
  },
  {
    rawText: "5 cosas que me hubiera gustado saber antes de automatizar mi negocio",
    onScreenText: "5 COSAS ANTES DE AUTOMATIZAR",
    views: 611_000,
    likes: 44_300,
    saves: 52_800,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "tiktok",
    sourceUrl: "https://tiktok.com/@tenfoldmarc/video/7300000000000000001",
    daysAgo: 9,
    tags: ["automatización", "negocio", "errores"],
  },
  {
    rawText: "La IA acaba de reemplazar a mi editor de video",
    onScreenText: "ADIÓS EDITOR",
    views: 528_000,
    likes: 41_700,
    saves: 22_400,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/Cx3cD4eF5gH",
    daysAgo: 12,
    tags: ["ia", "video", "herramientas"],
  },
  {
    rawText: "La plantilla exacta que uso para escribir hooks en 5 minutos",
    onScreenText: "PLANTILLA DE HOOKS · GRATIS",
    views: 493_000,
    likes: 39_800,
    saves: 61_300,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/Cx4dE5fG6hI",
    daysAgo: 15,
    tags: ["plantilla", "copywriting", "hooks"],
    isFavorite: true,
  },
  {
    rawText: "Cómo pasé de 0 a 40.000 seguidores en 6 meses",
    onScreenText: "0 → 40.000 EN 6 MESES",
    views: 456_000,
    likes: 36_200,
    saves: 27_900,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "youtube",
    sourceUrl: "https://youtube.com/shorts/aBcDeFgHiJk",
    daysAgo: 18,
    tags: ["crecimiento", "instagram", "caso"],
  },
  {
    rawText: "Si sigues comprando seguidores, para ya",
    onScreenText: "PARA YA · ESTO TE ESTÁ MATANDO",
    views: 388_000,
    likes: 31_400,
    saves: 18_200,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "tiktok",
    sourceUrl: "https://tiktok.com/@tenfoldmarc/video/7300000000000000002",
    daysAgo: 21,
    tags: ["advertencia", "seguidores", "algoritmo"],
  },
  {
    rawText: "El truco que usan los editores de Netflix para retener",
    onScreenText: "EL TRUCO DE NETFLIX",
    views: 351_000,
    likes: 28_600,
    saves: 24_100,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/Cx5eF6gH7iJ",
    daysAgo: 24,
    tags: ["retención", "edición", "storytelling"],
  },
  {
    rawText: "3 errores que te cuestan 10.000 seguidores al mes",
    onScreenText: "3 ERRORES = 10.000 SEGUIDORES",
    views: 312_000,
    likes: 24_900,
    saves: 26_700,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/Cx6fG7hI8jK",
    daysAgo: 28,
    tags: ["errores", "crecimiento", "instagram"],
  },
  {
    rawText: "Cómo crecí en TikTok sin mostrar la cara",
    onScreenText: "SIN CARA · +120K",
    views: 298_000,
    likes: 23_100,
    saves: 19_400,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "tiktok",
    sourceUrl: "https://tiktok.com/@tenfoldmarc/video/7300000000000000003",
    daysAgo: 32,
    tags: ["tiktok", "faceless", "crecimiento"],
  },
  {
    rawText: "¿Por qué el contenido feo sigue funcionando mejor?",
    onScreenText: "CONTENIDO FEO > CONTENIDO BONITO",
    views: 265_000,
    likes: 21_300,
    saves: 14_800,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/Cx7gH8iJ9kL",
    daysAgo: 36,
    tags: ["algoritmo", "contenido", "debate"],
  },
  {
    rawText: "Hace un año editaba hasta las 3am y hoy publico en 20 minutos",
    onScreenText: "3AM → 20 MINUTOS",
    views: 241_000,
    likes: 19_800,
    saves: 16_200,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/Cx8hI9jK0lM",
    daysAgo: 40,
    tags: ["historia", "productividad", "automatización"],
  },
  {
    rawText: "Nadie te dice la verdad sobre vivir de crear contenido",
    onScreenText: "LA VERDAD INCÓMODA",
    views: 228_000,
    likes: 20_400,
    saves: 13_900,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/Cx9iJ0kL1mN",
    daysAgo: 44,
    tags: ["verdad", "creadores", "negocio"],
  },
  {
    rawText: "Esta función de Notion desaparece en 30 días. Esto es lo que tienes que hacer",
    onScreenText: "30 DÍAS PARA ACTUAR",
    views: 196_000,
    likes: 15_700,
    saves: 12_100,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "threads",
    sourceUrl: "https://threads.net/@tenfoldmarc/post/CxA1",
    daysAgo: 48,
    tags: ["notion", "urgencia", "herramientas"],
  },
  {
    rawText: "El sistema paso a paso que uso para planificar 30 días de contenido",
    onScreenText: "30 DÍAS EN 1 TARDE",
    views: 187_000,
    likes: 16_200,
    saves: 22_800,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/CxB2kL3mN4o",
    daysAgo: 52,
    tags: ["sistema", "planificación", "calendario"],
  },
  {
    rawText: "7 señales de que tu contenido está bien y el algoritmo te está mintiendo",
    onScreenText: "7 SEÑALES",
    views: 174_000,
    likes: 14_100,
    saves: 11_600,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/CxC3lM4nO5p",
    daysAgo: 58,
    tags: ["algoritmo", "diagnóstico", "señales"],
  },
  {
    rawText: "Deja de gastar en ads antes de leer esto",
    onScreenText: "PARA ANTES DE GASTAR EN ADS",
    views: 163_000,
    likes: 13_400,
    saves: 15_700,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "linkedin",
    sourceUrl: "https://linkedin.com/feed/update/urn:li:activity:7200000000000000001",
    daysAgo: 63,
    tags: ["ads", "presupuesto", "marketing"],
  },
  {
    rawText: "Cómo lancé un producto digital en 9 días",
    onScreenText: "LANZAMIENTO EN 9 DÍAS",
    views: 152_000,
    likes: 12_800,
    saves: 10_400,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/CxD4mN5oP6q",
    daysAgo: 67,
    tags: ["lanzamiento", "producto", "caso"],
  },
  {
    rawText: "El prompt que uso para convertir una idea en 30 posts",
    onScreenText: "1 IDEA → 30 POSTS",
    views: 141_000,
    likes: 12_100,
    saves: 18_900,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/CxE5nO6pQ7r",
    daysAgo: 72,
    tags: ["prompt", "ia", "contenido"],
  },
  {
    rawText: "Si sigues midiendo solo los likes, para ya",
    onScreenText: "LOS LIKES NO IMPORTAN",
    views: 133_000,
    likes: 11_200,
    saves: 9_800,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/CxF6oP7qR8s",
    daysAgo: 78,
    tags: ["métricas", "analytics", "advertencia"],
  },
  {
    rawText: "4 formas de reutilizar un solo video durante un mes",
    onScreenText: "1 VIDEO → 30 DÍAS",
    views: 121_000,
    likes: 10_400,
    saves: 14_300,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "tiktok",
    sourceUrl: "https://tiktok.com/@tenfoldmarc/video/7300000000000000004",
    daysAgo: 84,
    tags: ["reutilización", "contenido", "productividad"],
  },
  {
    rawText: "Cómo cerré 3 clientes con un video de 20 segundos",
    onScreenText: "3 CLIENTES · 1 VIDEO",
    views: 114_000,
    likes: 9_700,
    saves: 8_600,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "instagram",
    sourceUrl: "https://instagram.com/reel/CxG7pQ8rS9t",
    daysAgo: 90,
    tags: ["clientes", "ventas", "caso"],
  },
  {
    rawText: "El truco que usan las agencias para cobrar el triple",
    onScreenText: "COBRAR 3X",
    views: 108_000,
    likes: 9_100,
    saves: 11_200,
    creatorHandle: "@tenfoldmarc",
    creatorPlatform: "linkedin",
    sourceUrl: "https://linkedin.com/feed/update/urn:li:activity:7200000000000000002",
    daysAgo: 96,
    tags: ["precios", "agencias", "negocio"],
  },
];

export function createSeedHooks(): Hook[] {
  return SEEDS.map((seed) =>
    buildHook({
      rawText: seed.rawText,
      onScreenText: seed.onScreenText,
      views: seed.views,
      likes: seed.likes,
      saves: seed.saves,
      creatorHandle: seed.creatorHandle,
      creatorPlatform: seed.creatorPlatform,
      sourceUrl: seed.sourceUrl,
      sourceReelId: seed.sourceUrl.split("/").pop(),
      savedAt: daysAgo(seed.daysAgo),
      tags: seed.tags,
      isFavorite: seed.isFavorite,
    }),
  );
}

export const SEED_HOOKS: Hook[] = createSeedHooks();
